# Generated by Django 5.2.5 on 2025-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("script", "New Script Generated"),
                    ("account", "Account or Plan Changes"),
                    ("feature", "Feature Updates"),
                    ("tips", "Tips & Content Inspiration"),
                    ("community", "Community or Affiliate Updates"),
                    ("subscription", "Subscription Updates"),
                    ("drafts", "Draft Reminders"),
                    ("title", "Title Optimizer"),
                ],
                default="script",
                max_length=50,
            ),
        ),
    ]
