# Generated by Django 5.2.5 on 2025-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
