# Generated by Django 5.2.5 on 2025-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_metadata_usernotification_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("script", "New Script Generated"),
                    ("account", "Account or Plan Changes"),
                    ("feature", "Feature Updates"),
                    ("tips", "Tips & Content Inspiration"),
                    ("community", "Community or Affiliate Updates"),
                    ("subscription", "Subscription Updates"),
                    ("drafts", "Draft Reminders"),
                    ("title", "Title Optimizer"),
                ],
                default="script",
                max_length=50,
                null=True,
            ),
        ),
    ]
