# Generated by Django 5.2.5 on 2025-09-10 19:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "min_length",
                    models.IntegerField(
                        help_text="Minimum expected length in characters or words"
                    ),
                ),
                (
                    "max_length",
                    models.IntegerField(
                        help_text="Maximum expected length in characters or words"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(help_text="Expected duration in seconds"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this template style"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description or summary of the script content"
                    ),
                ),
                (
                    "style",
                    models.TextField(
                        help_text="Style guidelines or formatting instructions"
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        help_text="Target length in characters or words"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="The actual script content"),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "template_style",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional template style to apply",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scripts",
                        to="scripts.templatestyle",
                    ),
                ),
                (
                    "tone",
                    models.ForeignKey(
                        help_text="The tone/vibe for this script",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripts",
                        to="scripts.tone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
