# Generated by Django 5.2.5 on 2025-09-13 10:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptOutline",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                (
                    "outline_data",
                    models.JSONField(
                        default=dict, help_text="Structured outline data from OpenAI"
                    ),
                ),
                ("outline_text", models.TextField(help_text="Editable outline text")),
                ("openai_model", models.CharField(default="gpt-4", max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "generation_time",
                    models.FloatField(default=0.0, help_text="Time in seconds"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("script_generated", "Script Generated"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "original_outline",
                    models.TextField(
                        blank=True, help_text="Original AI-generated outline"
                    ),
                ),
                (
                    "script",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outline",
                        to="scripts.script",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="FullScript",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField(help_text="Full script content")),
                (
                    "sections",
                    models.JSONField(
                        default=list, help_text="Script broken into sections/scenes"
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_duration",
                    models.FloatField(
                        default=0.0, help_text="Estimated duration in minutes"
                    ),
                ),
                ("openai_model", models.CharField(default="gpt-4", max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                ("generation_time", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("edited", "Edited"),
                            ("finalized", "Finalized"),
                            ("published", "Published"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="full_scripts",
                        to="scripts.scriptoutline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
