# Generated by Django 5.2.5 on 2025-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0002_scriptoutline_fullscript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptoutline",
            name="script",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional reference to original script (if created from script)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outline",
                to="scripts.script",
            ),
        ),
    ]
