# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_simplify_status_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='length',
        ),
        migrations.AddField(
            model_name='script',
            name='min_length',
            field=models.IntegerField(default=100, help_text='Minimum target length in characters or words'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='max_length',
            field=models.IntegerField(default=1000, help_text='Maximum target length in characters or words'),
            preserve_default=False,
        ),
    ]
