# Generated by Django 5.2.5 on 2025-09-18 08:26

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0005_script_length_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptTitle",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_optimized_title", models.BooleanField(default=False)),
                ("titles", models.JSONField(default=list)),
                ("titles_count", models.IntegerField(default=0)),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        help_text="Prompt used for title optimization",
                        null=True,
                    ),
                ),
                (
                    "user_provided_title",
                    models.TextField(
                        blank=True, help_text="User provided title", null=True
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="scripts.script",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
