# Generated by Django 5.2.5 on 2025-09-18 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0008_titletone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this script",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
