# Generated by Django 5.2.5 on 2025-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0010_alter_script_tones"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptoutline",
            name="tones",
            field=models.ManyToManyField(
                help_text="The tones/vibes for this outline",
                related_name="outlines",
                to="scripts.tone",
            ),
        ),
    ]
