# Generated by Django 5.2.5 on 2025-09-19 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0011_scriptoutline_tones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fullscript",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this full script",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="full_scripts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scriptoutline",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this script outline",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="script_outlines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
