# Generated by Django 5.2.5 on 2025-09-19 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0012_fullscript_user_scriptoutline_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scripttitle",
            name="script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="titles",
                to="scripts.fullscript",
            ),
        ),
    ]
