# Generated by Django 5.2.7 on 2025-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0013_alter_scripttitle_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptoutline",
            name="order",
            field=models.JSONField(
                default=list,
                help_text="Order array for outline sections that clients can update",
            ),
        ),
    ]
