# Generated by Django 5.2.7 on 2025-10-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0014_add_order_field_to_scriptoutline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scriptoutline",
            name="order",
        ),
        migrations.AddField(
            model_name="scriptoutline",
            name="section_order",
            field=models.JSONField(
                default=list,
                help_text="Array of section indices representing user's custom ordering of outline sections",
            ),
        ),
    ]
