# Generated by Django 5.2.7 on 2025-10-09 08:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0015_replace_order_with_section_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIRunLog",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(help_text="OpenAI thread ID", max_length=255),
                ),
                ("run_id", models.CharField(help_text="OpenAI run ID", max_length=255)),
                (
                    "assistant_id",
                    models.CharField(help_text="OpenAI assistant ID", max_length=255),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, help_text="Total tokens consumed"),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        default=0, help_text="Word count of generated output"
                    ),
                ),
                (
                    "file_search_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether file search (vector store) was used",
                    ),
                ),
                (
                    "file_search_snippets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sample of file search snippets/citations used",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("title_generation", "Title Generation"),
                            ("outline_generation", "Outline Generation"),
                            ("script_generation", "Script Generation"),
                            ("image_analysis", "Image Analysis"),
                        ],
                        help_text="Type of generation performed",
                        max_length=50,
                    ),
                ),
                (
                    "generation_time",
                    models.FloatField(default=0.0, help_text="Time in seconds"),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4", help_text="Model used", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "full_script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to="scripts.fullscript",
                    ),
                ),
                (
                    "script_outline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to="scripts.scriptoutline",
                    ),
                ),
                (
                    "script_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to="scripts.scripttitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this run",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openai_run_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["thread_id"], name="scripts_ope_thread__80d424_idx"
                    ),
                    models.Index(
                        fields=["run_id"], name="scripts_ope_run_id_058af5_idx"
                    ),
                    models.Index(
                        fields=["user", "-created"],
                        name="scripts_ope_user_id_023c68_idx",
                    ),
                ],
            },
        ),
    ]
