# Generated by Django 5.2.5 on 2025-10-10 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0016_openairunlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scriptoutline",
            name="script",
        ),
    ]
