# Generated by Django 5.2.7 on 2025-10-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0018_usertitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertitles',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertitles',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_generated_titles', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='usertitles',
            name='tones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usertitles',
            name='user_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
