# Generated by Django 5.2.7 on 2025-10-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_niche_prompt"),
        (
            "scripts",
            "0019_usertitles_prompt_usertitles_script_usertitles_tones_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptoutline",
            name="niche",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional niche style applied during generation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="script_outlines",
                to="admins.niche",
            ),
        ),
    ]
