import uuid

from django.contrib.auth import get_user_model
from django.db import models
from model_utils.models import TimeStampedModel

User = get_user_model()


class Tone(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class TemplateStyle(TimeStampedModel):
    name = models.CharField(max_length=200, unique=True)
    min_length = models.IntegerField(
        help_text="Minimum expected length in characters or words"
    )
    max_length = models.IntegerField(
        help_text="Maximum expected length in characters or words"
    )
    duration = models.IntegerField(help_text="Expected duration in seconds")
    description = models.TextField(
        blank=True, help_text="Description of this template style"
    )

    def __str__(self):
        return f"{self.name} ({self.min_length}-{self.max_length})"

    class Meta:
        ordering = ["name"]


class Script(TimeStampedModel):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="scripts",
        help_text="The user who owns this script",
        null=True,
        blank=True,
    )
    description = models.TextField(
        help_text="Description or summary of the script content"
    )
    style = models.TextField(help_text="Style guidelines or formatting instructions")
    min_length = models.IntegerField(
        help_text="Minimum target length in characters or words"
    )
    max_length = models.IntegerField(
        help_text="Maximum target length in characters or words"
    )
    tones = models.ManyToManyField(
        Tone, related_name="scripts", help_text="The tones/vibes for this script"
    )
    template_style = models.ForeignKey(
        TemplateStyle,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="scripts",
        help_text="Optional template style to apply",
    )
    content = models.TextField(blank=True, help_text="The actual script content")
    title = models.CharField(max_length=200, blank=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title or 'Script'} ({self.uuid})"

    class Meta:
        ordering = ["-created"]


class ScriptOutline(TimeStampedModel):
    """
    Editable script outline generated by OpenAI
    """

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="script_outlines",
        help_text="The user who owns this script outline",
        null=True,
        blank=True,
    )
    script = models.OneToOneField(
        "Script",
        on_delete=models.CASCADE,
        related_name="outline",
        null=True,
        blank=True,
        help_text="Optional reference to original script (if created from script)",
    )
    title = models.CharField(max_length=300, blank=True)

    # Tones for this outline (can be multiple)
    tones = models.ManyToManyField(
        Tone, related_name="outlines", help_text="The tones/vibes for this outline"
    )

    # Outline structure as JSON for flexibility
    outline_data = models.JSONField(
        default=dict, help_text="Structured outline data from OpenAI"
    )

    # Raw outline text for editing
    outline_text = models.TextField(help_text="Editable outline text")

    # Order field for client-side ordering
    order = models.JSONField(
        default=list, 
        help_text="Order array for outline sections that clients can update"
    )

    # OpenAI metadata
    openai_model = models.CharField(max_length=50, default="gpt-4")
    tokens_used = models.IntegerField(default=0)
    generation_time = models.FloatField(default=0.0, help_text="Time in seconds")

    # Status tracking
    STATUS_CHOICES = [
        ("draft", "Draft"),
        ("generated", "Generated"),
        ("saved", "Saved"),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")

    # Version control for edits
    version = models.PositiveIntegerField(default=1)
    original_outline = models.TextField(
        blank=True, help_text="Original AI-generated outline"
    )

    def __str__(self):
        script_title = self.script.title if self.script else "Direct Outline"
        return f"Outline for {script_title} v{self.version}"

    def save(self, *args, **kwargs):
        # Track if outline text was edited
        if self.pk and self.outline_text != self.original_outline:
            if self.status == "generated":
                self.status = "draft"
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-created"]


class FullScript(TimeStampedModel):
    """
    Full script generated from the outline
    """

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="full_scripts",
        help_text="The user who owns this full script",
        null=True,
        blank=True,
    )
    outline = models.ForeignKey(
        ScriptOutline, on_delete=models.CASCADE, related_name="full_scripts"
    )
    title = models.CharField(max_length=300)
    content = models.TextField(help_text="Full script content")

    # Script structure
    sections = models.JSONField(
        default=list, help_text="Script broken into sections/scenes"
    )
    word_count = models.PositiveIntegerField(default=0)
    estimated_duration = models.FloatField(
        default=0.0, help_text="Estimated duration in minutes"
    )
    openai_model = models.CharField(max_length=50, default="gpt-4")
    tokens_used = models.IntegerField(default=0)
    generation_time = models.FloatField(default=0.0)
    STATUS_CHOICES = [
        ("draft", "Draft"),
        ("generated", "Generated"),
        ("saved", "Saved"),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")
    version = models.PositiveIntegerField(default=1)
    is_published = models.BooleanField(default=False)
    published_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.content:
            self.word_count = len(self.content.split())
            self.estimated_duration = self.word_count / 150
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} v{self.version}"

    class Meta:
        ordering = ["-created"]


class ScriptTitle(TimeStampedModel):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="titles")
    script = models.ForeignKey(
        FullScript,
        on_delete=models.CASCADE,
        related_name="titles",
        null=True,
        blank=True,
    )
    is_optimized_title = models.BooleanField(default=False)
    titles = models.JSONField(default=list)
    titles_count = models.IntegerField(default=0)
    prompt = models.TextField(
        null=True, blank=True, help_text="Prompt used for title optimization"
    )
    user_provided_title = models.TextField(
        null=True, blank=True, help_text="User provided title"
    )


class TitleTone(TimeStampedModel):
    name = models.CharField(max_length=100, unique=True)
