# Generated by Django 5.2.5 on 2025-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("trial", "Trial Plan"),
                    ("basic", "Basic Plan"),
                    ("pro", "Pro Plan"),
                ],
                max_length=20,
            ),
        ),
    ]
