# Generated by Django 5.2.5 on 2025-09-11 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_subscriptionplan_billing_cycle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="user",
        ),
        migrations.DeleteModel(
            name="PaymentHistory",
        ),
        migrations.DeleteModel(
            name="UserSubscription",
        ),
    ]
