# Generated by Django 5.2.7 on 2025-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
