# Generated by Django 5.2.5 on 2025-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_emailverificationtoken"),
        ("users", "0003_user_is_email_verified_user_preferred_language_and_more"),
    ]

    operations = []
