# Generated by Django 5.2.5 on 2025-08-27 19:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_merge_20250827_1139"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("allow_product_update_emails", models.BooleanField(default=False)),
                ("allow_anonymized_data_usage", models.BooleanField(default=False)),
                ("in_app_notifications", models.BooleanField(default=False)),
                ("email_notifications", models.BooleanField(default=False)),
                ("web_push_notifications", models.BooleanField(default=False)),
                ("new_script_generated", models.BooleanField(default=False)),
                ("account_or_plan_changes", models.BooleanField(default=False)),
                ("tips_content_inspiration", models.BooleanField(default=False)),
                ("feature_updates", models.BooleanField(default=False)),
                ("community_affiliate_updates", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user settings",
                "verbose_name_plural": "user settings",
            },
        ),
    ]
