# Generated by Django 5.2.5 on 2025-09-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_blacklistedaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_used_trial",
            field=models.BooleanField(
                default=False,
                help_text="Tracks if user has already used their trial subscription",
            ),
        ),
    ]
