# Generated by Django 5.2.5 on 2025-09-27 06:12

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import users.models


def assign_default_role_to_existing_users(apps, schema_editor):
    """Assign the default 'user' role to all existing users"""
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")

    # Create default 'user' role if it doesn't exist
    user_role, created = Role.objects.get_or_create(
        name="user", defaults={"name": "user"}
    )

    # Assign the role to all existing users
    for user in User.objects.all():
        if not user.roles.exists():
            user.roles.add(user_role)


def reverse_assign_default_role(apps, schema_editor):
    """Remove role assignments (this is a no-op since we're not deleting users)"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_has_used_trial_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, default=users.models.get_default_user_roles, to="users.role"
            ),
        ),
        migrations.RunPython(
            assign_default_role_to_existing_users,
            reverse_assign_default_role,
        ),
    ]
