# Generated by Django 5.2.5 on 2025-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_role_user_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=255,
                unique=True,
            ),
        ),
    ]
