# Generated by Django 5.2.7 on 2025-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_role_options_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tolt_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text="Tolt's customer ID (links user to their referrer)", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tolt_partner_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tolt partner ID who referred this user', max_length=40, null=True),
        ),
    ]
