# Generated by Django 5.2.7 on 2025-11-03 22:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_tolt_customer_id_user_tolt_partner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('login_type', models.CharField(choices=[('google', 'Google OAuth'), ('magic_link', 'Magic Link'), ('admin', 'Admin Login')], help_text='Type of login method used', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the login request', null=True)),
                ('user', models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'db_table': 'login_logs',
                'indexes': [models.Index(fields=['-created'], name='login_logs_created_ad51a7_idx'), models.Index(fields=['user', '-created'], name='login_logs_user_id_a291dd_idx')],
            },
        ),
    ]
