# Generated by Django 5.2.8 on 2025-11-10 18:33

from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_loginlog"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
